### ISSUE TITLE
On licence file

### ISSUE THREAD

**Issue by mnhbanagare** [pedsm/planning-poker#46]
I hope this message finds you well. I've been looking through the this repo  and I've found it to be interesting , I can contribute some if needed. I noticed that there isn't a license file currently included. Would it be possible for you to add a license file? It would be help clarify the terms under which this project can be used !!
or if needed I can create MR

Thank you so much for your time and for sharing this valuable resource with the community. Looking forward to your response.

**Comment by pedsm** [comment]
Hey @mnhbanagare sorry for taking so long on this one but the repo should now contain a License file as of the latest Update 👍 thanks for flagging that up
